[package]
name = "auto-judge"
version = "1.0.0-beta.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros", "time"] }
reqwest = "0.12.9"
colored = "2.1.0"
scraper = "0.21.0"
indicatif = "0.17.8"
